http:
  port: 8080
admin:
  port: 9876
  host: localhost

apiEndpoints:
  vault-api:
    # You can leave host wildcarded so EG listens on any hostname
    host: '*'
    # match anything under /api
    paths: '/vaults/*'

serviceEndpoints:
  vault-service:
    # point at your vault-service container and port
    url: 'http://vault-service:3000'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit

pipelines:
  vault-pipeline:
    apiEndpoints:
      - vault-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: vault-service
              changeOrigin: true
