http:
  port: 8080
  
admin:
  port: 9876
  host: localhost

apiEndpoints:
  # vault-api:
  #   host: '*'
  #   paths: '/vaults/*'
    
  notification-api:
    host: '*'
    paths: '/notifications'
    
  file-api:
    host: '*'
    paths: '/files'


serviceEndpoints:
  # vault-service:
  #   url: 'http://vault-service:3000/'
    
  notification-service:
    url: 'http://lockbox-notification-service:8080/'
    
  file-service:
    url: 'http://lockbox-file-service:8081/'


policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit


pipelines:
  # vault-pipeline:
  #   apiEndpoints:
  #     - vault-api
  #   policies:
  #     - proxy:
  #         - action:
  #             serviceEndpoint: vault-service
  #             changeOrigin: true
  
  notification-pipeline:
    apiEndpoints:
      - notification-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: notification-service
              changeOrigin: true
            
  fileservice-pipeline:
    apiEndpoints:
      - file-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: file-service
              changeOrigin: true
              
